---
- name: ğŸ§© 1. Construir ISO Debian personalizada
  import_playbook: ../01debian-preseed/playbook.yml

- name: ğŸ’½ 2. Crear y configurar mÃ¡quinas virtuales (VirtualBox)
  import_playbook: ../02vbox-vms/playbook.yml

- name: ğŸ–¥ï¸ 3. Configurar hostname
  import_playbook: ../04hostname/playbook.yml

- name: ğŸŒ 4. Configurar zona horaria
  import_playbook: ../03timezone/playbook.yml

- name: ğŸ³ 5. Instalar Docker
  import_playbook: ../05install-docker/playbook.yml

- name: â˜¸ï¸ 6. Instalar MicroK8s
  import_playbook: ../06install-microk8s/playbook.yml
