vms:
  - name: "k8s-master"
    cpu: 3
    ram: 6144
    disk: 20000
    mac: "0800279E473A"
    iso_path: "/vm/iso/debian-13.1.0-amd64-netinst-custom.iso"
    basefolder: "/vm"
    nic_adapter: "enp43s0"

  - name: "k8s-worker"
    cpu: 3
    ram: 6144
    disk: 20000
    mac: "080027923B5C"
    iso_path: "/vm/iso/debian-13.1.0-amd64-netinst-custom.iso"
    basefolder: "/vm"
    nic_adapter: "enp43s0"

  - name: "k8s-tools"
    cpu: 3
    ram: 6144
    disk: 20000
    mac: "0800272762D6"
    iso_path: "/vm/iso/debian-13.1.0-amd64-netinst-custom.iso"
    basefolder: "/vm"
    nic_adapter: "enp43s0"

